### ISSUE TITLE
无法使用 for，while

### ISSUE THREAD

**Issue by SteveUbuntu0** [xingyujie/binpython#7]

**Comment by SteveUbuntu0** [comment]
![Uploading 0V2WGK5D0%3~_Z)MZJ@XKDQ.png…]()

**Comment by SteveUbuntu0** [comment]
![image](https://user-images.githubusercontent.com/96877658/179690642-67b41b8a-a52f-4857-8bcd-71d6c228f397.png)

**Comment by xingyujie** [comment]
您好， 感谢您的issues，稍候我们将核实此issues，可能是由于技术缺陷导致的，我们尽量尝试修复此issues，您可以尝试保存到.py文件查看是否可以使用。
稍候我们会尝试解决此问题。
Thank you for your issues, we will verify this issue later, it may be caused by technical defects, we will try our best to fix this issue, you can try to save it to a .py file to see if it can be used.
至此
敬礼
BINPython 开发者：xingyujie

**Comment by xingyujie** [comment]
目前已经找到问题，尽量在下个版本修复
将会关闭此issues
